#!/bin/bash

picom &

nm-applet&

killall -q polybar

polybar example &

polybar example1 &

nitrogen --restore &

sxhkd &

~/.screenlayout/resolution1.sh 

bspc monitor eDP1 -d 1 2 3 4 5

bspc monitor DP1 -d 6 7 8 9

bspc config border_width 2

bspc config focused_border_color "#005fff"

bspc config normal_border_color "#000000"

bspc config top_padding 22

bspc config window_gap 16

bspc rule -a Lxappearance state=floating 

bspc rule -a Pcmanfm state=floating

bspc rule -a Pavucontrol state=floating
